// This file is generated by packages/core/build/generate-components.mjs.
// Do not edit manually.

import type { Plugin } from 'vue'

import {
  MoeAlert,
  MoeButton,
  MoeButtonGroup,
  MoeCollapse,
  MoeCollapseItem,
  MoeConfigProvider,
  MoeDropdown,
  MoeDropdownItem,
  MoeDropdownMenu,
  MoeForm,
  MoeFormItem,
  MoeIcon,
  MoeInput,
  MoeLoading,
  MoeMessage,
  MoeMessageBox,
  MoeNotification,
  MoePopconfirm,
  MoeSelect,
  MoeOption,
  MoeSwitch,
  MoeTooltip,
} from '@moe-ui/components'

export default [
  MoeAlert,
  MoeButton,
  MoeButtonGroup,
  MoeCollapse,
  MoeCollapseItem,
  MoeConfigProvider,
  MoeDropdown,
  MoeDropdownItem,
  MoeDropdownMenu,
  MoeForm,
  MoeFormItem,
  MoeIcon,
  MoeInput,
  MoeLoading,
  MoeMessage,
  MoeMessageBox,
  MoeNotification,
  MoePopconfirm,
  MoeSelect,
  MoeOption,
  MoeSwitch,
  MoeTooltip,
] as Plugin[]
