// This file is generated by packages/core/build/generate-components.mjs.
// Do not edit manually.

import {
  MoeAlert,
  MoeButton,
  MoeButtonGroup,
  MoeCollapse,
  MoeCollapseItem,
  MoeDropdown,
  MoeDropdownItem,
  MoeDropdownMenu,
  MoeIcon,
  MoeInput,
  MoeLoading,
  MoeMessage,
  MoeMessageBox,
  MoeNotification,
  MoePopconfirm,
  MoeSelect,
  MoeOption,
  MoeSwitch,
  MoeTooltip,
} from '@moe-ui/components'
import type { Plugin } from 'vue'

export default [
  MoeAlert,
  MoeButton,
  MoeButtonGroup,
  MoeCollapse,
  MoeCollapseItem,
  MoeDropdown,
  MoeDropdownItem,
  MoeDropdownMenu,
  MoeIcon,
  MoeInput,
  MoeLoading,
  MoeMessage,
  MoeMessageBox,
  MoeNotification,
  MoePopconfirm,
  MoeSelect,
  MoeOption,
  MoeSwitch,
  MoeTooltip,
] as Plugin[]
