// This file is generated by packages/core/build/generate-components.mjs.
// Do not edit manually.

export interface MoeUIResolverOptions {
  /**
   * Import component styles automatically.
   *
   * @default 'css'
   */
  importStyle?: boolean | 'css'
}

export interface MoeUIResolvedImport {
  name: string
  from: string
  sideEffects?: string
}

const PACKAGE_NAME = 'moe-cute-ui'

const componentEntryMap: Record<string, string> = {
  MoeAlert: 'Alert',
  MoeButton: 'Button',
  MoeButtonGroup: 'Button',
  MoeCollapse: 'Collapse',
  MoeCollapseItem: 'Collapse',
  MoeConfigProvider: 'ConfigProvider',
  MoeDropdown: 'Dropdown',
  MoeDropdownItem: 'Dropdown',
  MoeDropdownMenu: 'Dropdown',
  MoeForm: 'Form',
  MoeFormItem: 'Form',
  MoeIcon: 'Icon',
  MoeInput: 'Input',
  MoeLoading: 'Loading',
  MoeMessage: 'Message',
  MoeMessageBox: 'MessageBox',
  MoeNotification: 'Notification',
  MoePopconfirm: 'Popconfirm',
  MoeSelect: 'Select',
  MoeOption: 'Select',
  MoeSwitch: 'Switch',
  MoeTooltip: 'Tooltip',
}

function resolveEntryName(name: string) {
  return componentEntryMap[name]
}

function getSideEffects(entryName: string, importStyle: MoeUIResolverOptions['importStyle']) {
  if (!importStyle) return undefined

  return `${PACKAGE_NAME}/es/components/${entryName}/style/css`
}

export function MoeUIResolver(options: MoeUIResolverOptions = {}) {
  const { importStyle = 'css' } = options

  return {
    resolve(name: string): MoeUIResolvedImport | undefined {
      const entryName = resolveEntryName(name)

      if (!entryName) return undefined

      return {
        name,
        from: `${PACKAGE_NAME}/es/components/${entryName}`,
        sideEffects: getSideEffects(entryName, importStyle),
      }
    },
  }
}
